# Generated by Django 5.1.5 on 2025-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Artist name'),
        ),
    ]
