# Generated by Django 5.1.5 on 2025-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_spotify', '0002_alter_album_publication_date_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
